"""Extract binary class masks from a CVAT Segmentation Mask ZIP archive.

The output contains one directory per requested class. Every generated PNG is a
single-channel image where 255 (white) belongs to the class and 0 is background.
"""

from __future__ import annotations

import argparse
import io
import json
import re
import shutil
import zipfile
from pathlib import Path, PurePosixPath
from typing import Any

import numpy as np
from PIL import Image


DEFAULT_CLASSES = {
    "Door": "puerta",
    "Ground": "camino_transitable",
    "Wall": "muro",
}

# Carpeta creada desde CVAT -> carpeta creada por extractVideoFrames.py.
VIDEO_MASK_FOLDERS = {
    "puerta": "puerta",
    "camino_transitable": "camino_transitable",
    "muro": "muro",
}

GENERATED_MASK_FOLDERS = {*DEFAULT_CLASSES.values(), "suelo"}


def clean_generated_mask_dirs(output_dir: Path) -> None:
    """Remove only the class directories generated by this script."""
    for folder in GENERATED_MASK_FOLDERS:
        generated_dir = output_dir / folder
        if generated_dir.is_dir():
            shutil.rmtree(generated_dir)


def _safe_div(numerator: int, denominator: int) -> float:
    return float(numerator) / float(denominator) if denominator else 0.0


def _metrics_from_totals(totals: dict[str, int]) -> dict[str, Any]:
    """Calculate micro-averaged metrics from accumulated pixel counts."""
    tp, fp, fn, tn = (totals[key] for key in ("tp", "fp", "fn", "tn"))
    return {
        **totals,
        "iou": _safe_div(tp, tp + fp + fn),
        "dice": _safe_div(2 * tp, 2 * tp + fp + fn),
        "precision": _safe_div(tp, tp + fp),
        "recall": _safe_div(tp, tp + fn),
        "accuracy": _safe_div(tp + tn, tp + fp + fn + tn),
    }


def _metrics(reference: np.ndarray, prediction: np.ndarray) -> dict[str, Any]:
    """Calculate binary segmentation metrics for a pair of masks."""
    reference = reference.astype(bool)
    prediction = prediction.astype(bool)
    totals = {
        "tp": int(np.logical_and(reference, prediction).sum()),
        "fp": int(np.logical_and(~reference, prediction).sum()),
        "fn": int(np.logical_and(reference, ~prediction).sum()),
        "tn": int(np.logical_and(~reference, ~prediction).sum()),
    }
    return _metrics_from_totals(totals)


def compare_masks(annotation_dir: Path, video_data_dir: Path) -> dict[str, Any]:
    """Compare CVAT and video masks whose filenames match exactly."""
    report: dict[str, Any] = {"classes": {}}

    for annotation_folder, video_folder in VIDEO_MASK_FOLDERS.items():
        reference_dir = annotation_dir / annotation_folder
        prediction_dir = video_data_dir / video_folder
        if not prediction_dir.is_dir():
            raise FileNotFoundError(
                f"No existe la carpeta de mascaras del video: {prediction_dir}"
            )

        prediction_files = {
            path.name.casefold(): path
            for path in prediction_dir.iterdir()
            if path.is_file() and path.suffix.casefold() == ".png"
        }
        items: list[dict[str, Any]] = []
        missing: list[str] = []
        totals = {key: 0 for key in ("tp", "fp", "fn", "tn")}

        for reference_path in sorted(reference_dir.glob("*.png")):
            prediction_path = prediction_files.get(reference_path.name.casefold())
            if prediction_path is None:
                missing.append(reference_path.name)
                continue

            with Image.open(reference_path) as image:
                reference = np.asarray(image.convert("L")) > 0
            with Image.open(prediction_path) as image:
                prediction = np.asarray(image.convert("L")) > 0

            if reference.shape != prediction.shape:
                raise ValueError(
                    f"Dimensiones diferentes para {reference_path.name} "
                    f"({annotation_folder}: {reference.shape}, "
                    f"{video_folder}: {prediction.shape})"
                )

            item_metrics = _metrics(reference, prediction)
            for key in totals:
                totals[key] += item_metrics[key]
            items.append({"filename": reference_path.name, **item_metrics})

        report["classes"][annotation_folder] = {
            "video_folder": video_folder,
            "matched": len(items),
            "missing_in_video_data": missing,
            "metrics": _metrics_from_totals(totals),
            "files": items,
        }

    return report


def read_labelmap(archive: zipfile.ZipFile) -> dict[str, tuple[int, int, int]]:
    """Return ``label -> RGB color`` entries from CVAT's labelmap.txt."""
    try:
        content = archive.read("labelmap.txt").decode("utf-8-sig")
    except KeyError as exc:
        raise ValueError("El ZIP no contiene labelmap.txt") from exc

    colors: dict[str, tuple[int, int, int]] = {}
    pattern = re.compile(r"^\s*([^#:]+?)\s*:\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*:")
    for line in content.splitlines():
        match = pattern.match(line)
        if match:
            colors[match.group(1).strip().casefold()] = tuple(
                int(value) for value in match.groups()[1:]
            )
    return colors


def extract_masks(
    archive_path: Path,
    output_dir: Path,
    classes: dict[str, str] = DEFAULT_CLASSES,
) -> dict[str, int]:
    """Extract one binary PNG per class and source image."""
    if not archive_path.is_file():
        raise FileNotFoundError(f"No existe el archivo: {archive_path}")

    counts = {folder: 0 for folder in classes.values()}
    with zipfile.ZipFile(archive_path) as archive:
        label_colors = read_labelmap(archive)
        missing = [name for name in classes if name.casefold() not in label_colors]
        if missing:
            raise ValueError(
                "Clases ausentes en labelmap.txt: " + ", ".join(missing)
            )

        members = sorted(
            name
            for name in archive.namelist()
            if name.startswith("SegmentationClass/") and name.lower().endswith(".png")
        )
        if not members:
            raise ValueError("El ZIP no contiene PNG en SegmentationClass/")

        for folder in classes.values():
            (output_dir / folder).mkdir(parents=True, exist_ok=True)

        for member in members:
            filename = PurePosixPath(member).name
            with Image.open(io.BytesIO(archive.read(member))) as image:
                rgb = np.asarray(image.convert("RGB"))

            for label, folder in classes.items():
                color = np.asarray(label_colors[label.casefold()], dtype=np.uint8)
                binary = np.all(rgb == color, axis=2).astype(np.uint8) * 255
                Image.fromarray(binary, mode="L").save(output_dir / folder / filename)
                counts[folder] += 1

    return counts


def find_single_zip(assets_dir: Path) -> Path:
    archives = sorted(assets_dir.glob("*.zip"))
    if not archives:
        raise FileNotFoundError(f"No se encontró ningún ZIP en {assets_dir}")
    if len(archives) > 1:
        names = ", ".join(path.name for path in archives)
        raise ValueError(f"Hay varios ZIP ({names}); indica uno con --archive")
    return archives[0]


def parse_args() -> argparse.Namespace:
    video_test_dir = Path(__file__).resolve().parent.parent
    default_assets = video_test_dir / "videos" / "assets"
    parser = argparse.ArgumentParser(
        description="Separa las máscaras de CVAT en puerta, suelo y muro."
    )
    parser.add_argument(
        "--archive",
        type=Path,
        help="ZIP exportado por CVAT (por defecto, el único ZIP de assets).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=default_assets,
        help="Carpeta de salida.",
    )
    parser.add_argument(
        "--video-data",
        type=Path,
        default=video_test_dir / "data",
        help="Carpeta data del video que contiene las mascaras a comparar.",
    )
    parser.add_argument(
        "--report",
        type=Path,
        default=video_test_dir / "results" / "annotation_mask_comparison.json",
        help="Archivo JSON donde se guardan las metricas de comparacion.",
    )
    parser.set_defaults(assets_dir=default_assets)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    archive = args.archive or find_single_zip(args.assets_dir)
    counts = extract_masks(archive.resolve(), args.output.resolve())
    print(f"Archivo procesado: {archive.resolve()}")
    print(f"Salida: {args.output.resolve()}")
    for class_name, count in counts.items():
        print(f"  {class_name}: {count} máscaras")

    report = compare_masks(args.output.resolve(), args.video_data.resolve())
    report_path = args.report.resolve()
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(
        json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(f"Comparacion guardada en: {report_path}")
    for class_name, result in report["classes"].items():
        metrics = result["metrics"]
        print(
            f"  {class_name} -> {result['video_folder']}: "
            f"{result['matched']} coincidencias, "
            f"IoU={metrics['iou']:.4f}, Dice={metrics['dice']:.4f}, "
            f"sin pareja={len(result['missing_in_video_data'])}"
        )

    clean_generated_mask_dirs(args.output.resolve())
    print(f"Carpetas de mascaras eliminadas de: {args.output.resolve()}")


if __name__ == "__main__":
    main()
