"""Segment synchronized RGB and raw RealSense depth image pairs.

Input generated by createHDF5.py:

    tests/video/videos/capture.h5

Before processing, RGB/, depth/, and capture_metadata.json are reconstructed
from the HDF5 file.

Output:

    tests/video/data/RGB/frame_000001.png
    tests/video/data/overlay/frame_000001.png
    tests/video/data/puerta/frame_000001.png
    tests/video/data/muro/frame_000001.png
    tests/video/data/camino_transitable/frame_000001.png
"""

from __future__ import annotations

import argparse
import faulthandler
faulthandler.enable()

import gc
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Optional

import numpy as np

THIS_DIR = Path(__file__).resolve().parent
REPO_ROOT = THIS_DIR.parents[1]
SRC_DIR = REPO_ROOT / "src"
for path in (REPO_ROOT, SRC_DIR):
    path_str = str(path)
    if path_str not in sys.path:
        sys.path.insert(0, path_str)

cp = None
cv2 = None
dataset_frames = None
segmentacion = None


DEFAULT_INPUT_DIR = THIS_DIR / "videos"
DEFAULT_OUTPUT_DIR = THIS_DIR / "data"
DEFAULT_HDF5_NAME = "capture.h5"
PREVIEW_WINDOW = "Frame processing: RGB | Segmentation (Q or Esc to stop)"


class FrameCache:
    """Expose one in-memory RGB-D pair through the dataset loader API."""

    def __init__(self) -> None:
        self.rgb_bgr: Optional[np.ndarray] = None
        self.depth_m: Optional[np.ndarray] = None

    def set_frame(self, rgb_bgr: np.ndarray, depth_m: np.ndarray) -> None:
        self.rgb_bgr = rgb_bgr
        self.depth_m = depth_m

    def load(self, index=None):
        del index
        if self.rgb_bgr is None or self.depth_m is None:
            return None, None
        return self.rgb_bgr, self.depth_m


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Segment synchronized RGB and raw depth PNG pairs."
    )
    parser.add_argument(
        "--input",
        "--video-dir",
        dest="input_dir",
        type=Path,
        default=DEFAULT_INPUT_DIR,
        help="Folder containing RGB/, depth/, and capture_metadata.json.",
    )
    parser.add_argument(
        "--h5",
        type=Path,
        default=None,
        help="HDF5 capture path. Defaults to input/capture.h5.",
    )
    parser.add_argument(
        "--extract-only",
        action="store_true",
        help=argparse.SUPPRESS,
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Output folder where RGB/ and overlay/ are created.",
    )
    parser.add_argument(
        "--metadata",
        type=Path,
        default=None,
        help="Metadata path. Defaults to input/capture_metadata.json.",
    )
    parser.add_argument(
        "--start-index",
        type=int,
        default=1,
        help="First number used for output filenames.",
    )
    parser.add_argument(
        "--max-frames",
        type=int,
        default=0,
        help="Maximum selected pairs to process. Use 0 for all.",
    )
    parser.add_argument(
        "--retry",
        type=int,
        default=2,
        help="Additional segmentation attempts when no mask is detected.",
    )
    parser.add_argument(
        "--no-preview",
        action="store_false",
        dest="preview",
        help="Process without opening the RGB/segmentation window.",
    )
    parser.set_defaults(preview=True)
    return parser.parse_args()


def load_processing_runtime() -> None:
    global cp, cv2, dataset_frames, segmentacion
    if cp is not None and dataset_frames is not None and segmentacion is not None:
        return
    try:
        import cupy as cupy_module

        cp = cupy_module
        print("Initializing CUDA/cuBLAS before segmentation imports...", flush=True)
        verify_cuda_runtime()

        import cv2 as cv2_module
        from application.gestorFotogramas import dataset_frames as frames_module
        from application.segmentacion import segmentacion as segmentation_module
    except ImportError as exc:
        raise RuntimeError(
            "RGB and depth were extracted, but the segmentation dependencies "
            "are unavailable."
        ) from exc
    cv2 = cv2_module
    dataset_frames = frames_module
    segmentacion = segmentation_module


def verify_cuda_runtime() -> None:
    """Initialize CUDA/cuBLAS once and report usable GPU memory."""
    try:
        device = cp.cuda.Device(0)
        device.use()
        cp.get_default_memory_pool().free_all_blocks()
        cp.get_default_pinned_memory_pool().free_all_blocks()
        gc.collect()

        free_bytes, total_bytes = cp.cuda.runtime.memGetInfo()
        free_mb = free_bytes / (1024 * 1024)
        total_mb = total_bytes / (1024 * 1024)
        print(
            f"CUDA device 0 memory: {free_mb:.0f} MiB free / "
            f"{total_mb:.0f} MiB total",
            flush=True,
        )

        left = cp.ones((2, 3), dtype=cp.float32)
        right = cp.ones((3, 2), dtype=cp.float32)
        result = left @ right
        cp.cuda.runtime.deviceSynchronize()
        if result.shape != (2, 2):
            raise RuntimeError("Unexpected cuBLAS test result.")
        del left, right, result
        cp.get_default_memory_pool().free_all_blocks()
        print("CUDA/cuBLAS preflight: OK", flush=True)
    except Exception as exc:
        raise RuntimeError(
            "CUDA/cuBLAS preflight failed before frame processing. "
            "CUBLAS_STATUS_NOT_INITIALIZED usually means insufficient shared "
            "memory on Jetson or an incompatible CuPy/CUDA installation. "
            f"Original error: {exc}"
        ) from exc


def extract_capture_hdf5(path: Path, output_dir: Path) -> Path:
    """Recreate RGB/depth PNG folders and metadata from an HDF5 capture."""
    global cv2
    import h5py

    if not path.is_file():
        raise FileNotFoundError(
            f"HDF5 capture not found: {path}. Run createHDF5.py first."
        )

    print(f"Opening HDF5 capture: {path}", flush=True)
    with h5py.File(path, "r") as source:
        if "rgb" not in source or "depth" not in source:
            raise ValueError(f"HDF5 file must contain rgb and depth datasets: {path}")
        rgb_dataset = source["rgb"]
        depth_dataset = source["depth"]
        if len(rgb_dataset) != len(depth_dataset):
            raise ValueError(
                "HDF5 RGB/depth frame counts differ: "
                f"{len(rgb_dataset)} versus {len(depth_dataset)}."
            )

        metadata_json = source.attrs.get("metadata_json")
        if metadata_json is None:
            raise ValueError(f"HDF5 file has no metadata_json attribute: {path}")
        if isinstance(metadata_json, bytes):
            metadata_json = metadata_json.decode("utf-8")
        metadata = json.loads(str(metadata_json))
        metadata["frame_count"] = len(rgb_dataset)

        rgb_pattern = str(metadata["rgb_pattern"])
        depth_pattern = str(metadata["depth_pattern"])
        rgb_suffix = Path(rgb_pattern.replace("%06d", "000001")).suffix
        depth_suffix = Path(depth_pattern.replace("%06d", "000001")).suffix
        jpeg_quality = int(metadata["rgb_jpeg_quality"])
        png_compression = int(metadata["depth_png_compression"])
        if not 0 <= jpeg_quality <= 100:
            raise ValueError("rgb_jpeg_quality must be between 0 and 100.")
        if not 0 <= png_compression <= 9:
            raise ValueError("depth_png_compression must be between 0 and 9.")

        rgb_dir = output_dir / str(metadata["rgb_directory"])
        depth_dir = output_dir / str(metadata["depth_directory"])
        for directory in (rgb_dir, depth_dir):
            directory.mkdir(parents=True, exist_ok=True)
            for old_frame in directory.glob("frame_*.*"):
                old_frame.unlink()

        filenames = source.get("filenames")
        encoded_images = int(source.attrs.get("format_version", 1)) >= 2
        if not encoded_images and cv2 is None:
            import cv2 as cv2_module

            cv2 = cv2_module
        for index in range(len(rgb_dataset)):
            if filenames is None:
                frame_stem = f"frame_{index + 1:06d}"
            else:
                stored_name = filenames[index]
                if isinstance(stored_name, bytes):
                    stored_name = stored_name.decode("utf-8")
                frame_stem = Path(str(stored_name)).stem

            rgb_path = rgb_dir / f"{frame_stem}{rgb_suffix}"
            depth_path = depth_dir / f"{frame_stem}{depth_suffix}"
            if encoded_images:
                rgb_bytes = bytes(rgb_dataset[index])
                depth_bytes = bytes(depth_dataset[index])
                if not rgb_bytes.startswith(b"\xff\xd8"):
                    raise ValueError(f"Invalid JPEG data in HDF5 frame {index}.")
                if not depth_bytes.startswith(b"\x89PNG\r\n\x1a\n"):
                    raise ValueError(f"Invalid PNG data in HDF5 frame {index}.")
                rgb_path.write_bytes(rgb_bytes)
                depth_path.write_bytes(depth_bytes)
            else:
                rgb = np.asarray(rgb_dataset[index])
                depth = np.asarray(depth_dataset[index])
                if rgb.ndim != 3 or rgb.shape[2] != 3 or rgb.dtype != np.uint8:
                    raise ValueError(
                        f"Invalid RGB frame {index}: "
                        f"shape={rgb.shape}, dtype={rgb.dtype}"
                    )
                if depth.ndim != 2 or depth.dtype != np.uint16:
                    raise ValueError(
                        f"Invalid depth frame {index}: "
                        f"shape={depth.shape}, dtype={depth.dtype}"
                    )

                rgb_bgr = cv2.cvtColor(rgb, cv2.COLOR_RGB2BGR)
                write_image(
                    rgb_path,
                    rgb_bgr,
                    "extracted RGB frame",
                    [cv2.IMWRITE_JPEG_QUALITY, jpeg_quality],
                )
                write_image(
                    depth_path,
                    depth,
                    "extracted depth frame",
                    [cv2.IMWRITE_PNG_COMPRESSION, png_compression],
                )
            print(
                f"\rExtracted HDF5 pairs: {index + 1}/{len(rgb_dataset)}",
                end="",
                flush=True,
            )

    metadata_path = output_dir / "capture_metadata.json"
    metadata_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    print(f"\nRecreated RGB and depth folders from: {path}")
    return metadata_path


def run_extraction_worker(hdf5_path: Path, input_dir: Path) -> Path:
    command = [
        sys.executable,
        str(Path(__file__).resolve()),
        "--extract-only",
        "--input",
        str(input_dir),
        "--h5",
        str(hdf5_path),
    ]
    subprocess.run(command, check=True)
    return input_dir / "capture_metadata.json"


def load_metadata(path: Path) -> dict:
    if not path.is_file():
        raise FileNotFoundError(
            f"Capture metadata not found: {path}. Run captureVideo.py first."
        )

    metadata = json.loads(path.read_text(encoding="utf-8"))
    if metadata.get("rgb_storage") not in ("png_sequence", "jpeg_sequence"):
        raise ValueError(
            "Unsupported RGB storage. Record again with the updated "
            "captureVideo.py to create synchronized RGB-D pairs."
        )
    if metadata.get("depth_storage") != "uint16_png_sequence":
        raise ValueError(
            "Unsupported depth storage. Record again with the updated "
            "captureVideo.py to store raw uint16 depth."
        )
    for key in (
        "rgb_directory",
        "rgb_pattern",
        "rgb_jpeg_quality",
        "depth_directory",
        "depth_pattern",
        "depth_png_compression",
    ):
        if key not in metadata:
            raise ValueError(f"capture_metadata.json is missing {key}.")
    if float(metadata.get("depth_scale", 0)) <= 0:
        raise ValueError("capture_metadata.json has an invalid depth_scale.")

    intrinsics = metadata.get("color_intrinsics")
    if not isinstance(intrinsics, dict):
        raise ValueError("capture_metadata.json has no color_intrinsics.")
    for key in ("width", "height", "fx", "fy", "ppx", "ppy"):
        if key not in intrinsics:
            raise ValueError(f"Missing color_intrinsics.{key} in {path}")
    return metadata


def create_and_clean_output_dirs(
    output_dir: Path,
) -> tuple[Path, Path, dict[str, Path]]:
    rgb_dir = output_dir / "RGB"
    overlay_dir = output_dir / "overlay"
    mask_dirs = {
        "door": output_dir / "puerta",
        "wall": output_dir / "muro",
        "ground": output_dir / "camino_transitable",
    }

    for directory in (rgb_dir, overlay_dir, *mask_dirs.values()):
        directory.mkdir(parents=True, exist_ok=True)
        for item in directory.iterdir():
            if item.is_symlink() or item.is_file():
                item.unlink()
            elif item.is_dir():
                shutil.rmtree(item)
            else:
                item.unlink()

    return rgb_dir, overlay_dir, mask_dirs


def list_rgb_frames(input_dir: Path, metadata: dict) -> list[Path]:
    rgb_dir = input_dir / metadata["rgb_directory"]
    pattern = str(metadata["rgb_pattern"])
    suffix = Path(pattern.replace("%06d", "000001")).suffix
    frames = sorted(rgb_dir.glob(f"frame_*{suffix}"))
    if not frames:
        raise FileNotFoundError(f"No RGB frames found in: {rgb_dir}")
    return frames


def load_frame_pair(
    rgb_path: Path,
    input_dir: Path,
    metadata: dict,
) -> tuple[np.ndarray, np.ndarray]:
    depth_dir = input_dir / metadata["depth_directory"]
    pattern = str(metadata["depth_pattern"])
    suffix = Path(pattern.replace("%06d", "000001")).suffix
    depth_path = depth_dir / f"{rgb_path.stem}{suffix}"

    rgb_bgr = cv2.imread(str(rgb_path), cv2.IMREAD_COLOR)
    depth_raw = cv2.imread(str(depth_path), cv2.IMREAD_UNCHANGED)
    if rgb_bgr is None:
        raise RuntimeError(f"Could not read RGB frame: {rgb_path}")
    if depth_raw is None:
        raise RuntimeError(
            f"RGB frame has no associated depth frame: {depth_path}"
        )
    if depth_raw.ndim != 2 or depth_raw.dtype != np.uint16:
        raise ValueError(
            f"Depth must be a lossless single-channel uint16 PNG: {depth_path}; "
            f"received shape={depth_raw.shape}, dtype={depth_raw.dtype}."
        )

    if depth_raw.shape != rgb_bgr.shape[:2]:
        depth_raw = cv2.resize(
            depth_raw,
            (rgb_bgr.shape[1], rgb_bgr.shape[0]),
            interpolation=cv2.INTER_NEAREST,
        )

    depth_scale = float(metadata["depth_scale"])
    depth_m = depth_raw.astype(np.float32) * depth_scale
    return rgb_bgr, depth_m


def compute_rays(
    intrinsics: dict,
    shape_hw: tuple[int, int],
) -> np.ndarray:
    height, width = shape_hw
    scale_x = width / float(intrinsics["width"])
    scale_y = height / float(intrinsics["height"])
    fx = float(intrinsics["fx"]) * scale_x
    fy = float(intrinsics["fy"]) * scale_y
    ppx = float(intrinsics["ppx"]) * scale_x
    ppy = float(intrinsics["ppy"]) * scale_y

    u = np.arange(width, dtype=np.float32)
    v = np.arange(height, dtype=np.float32)
    uu, vv = np.meshgrid(u, v)
    x = (uu - ppx) / fx
    y = (vv - ppy) / fy
    return np.stack((x, y, np.ones_like(x)), axis=-1).astype(np.float32)


def apply_camera_geometry(intrinsics: dict, shape_hw: tuple[int, int]) -> None:
    runtime = segmentacion._obtener_impl()
    height, width = shape_hw
    runtime["H"] = height
    runtime["W"] = width
    runtime["rays_cp"] = cp.asarray(compute_rays(intrinsics, shape_hw))
    runtime["mode"] = "camera"


def mask_has_pixels(mask) -> bool:
    if mask is None:
        return False
    try:
        return bool(cp.any(mask).item())
    except Exception:
        return bool(np.any(np.asarray(mask)))


def binary_mask(mask, shape_hw: tuple[int, int]) -> np.ndarray:
    """Convert a CPU/GPU segmentation mask to a uint8 binary PNG image."""
    if mask is None:
        return np.zeros(shape_hw, dtype=np.uint8)
    try:
        array = cp.asnumpy(mask)
    except Exception:
        array = np.asarray(mask)
    array = np.squeeze(array)
    if array.ndim != 2:
        raise ValueError(f"Invalid segmentation mask shape: {array.shape}")
    array = (array > 0).astype(np.uint8)
    if array.shape != shape_hw:
        array = cv2.resize(
            array,
            (shape_hw[1], shape_hw[0]),
            interpolation=cv2.INTER_NEAREST,
        )
    return array * 255


def process_frame(
    cache: FrameCache,
    dataset_index: int,
    retry: int,
    intrinsics: dict,
) -> tuple[Optional[np.ndarray], bool, dict]:
    dataset_frames.load_dataset_frame = cache.load
    ok = segmentacion.preprocesar(
        mode="prueba",
        dataset_index=dataset_index,
    )
    if not ok or cache.rgb_bgr is None:
        return None, False, {}

    apply_camera_geometry(intrinsics, cache.rgb_bgr.shape[:2])
    overlay = None
    detected = False
    masks = {}
    attempts = max(0, int(retry)) + 1

    for attempt in range(attempts):
        try:
            overlay = segmentacion.segmentar()
            masks = segmentacion.obtener_mascaras(copy=True) or {}
            detected = any(mask_has_pixels(mask) for mask in masks.values())
        except Exception as exc:
            print(
                f"\nSegmentation attempt {attempt + 1}/{attempts} failed "
                f"for source frame {dataset_index}: {exc}",
                file=sys.stderr,
            )
            error_text = str(exc).upper()
            if "CUBLAS_STATUS" in error_text or "CUDA_ERROR" in error_text:
                raise RuntimeError(
                    f"Fatal CUDA failure on source frame {dataset_index}: {exc}"
                ) from exc
            overlay = None
            detected = False
            masks = {}

        if overlay is not None and detected:
            break

    return overlay, detected, masks


def write_image(
    path: Path,
    image: np.ndarray,
    label: str,
    params: Optional[list[int]] = None,
) -> None:
    if not cv2.imwrite(str(path), image, params or []):
        raise RuntimeError(f"Could not save {label}: {path}")


def show_preview(
    rgb_bgr: np.ndarray,
    overlay: np.ndarray,
    detected: bool,
) -> bool:
    if overlay.shape[:2] != rgb_bgr.shape[:2]:
        overlay = cv2.resize(
            overlay,
            (rgb_bgr.shape[1], rgb_bgr.shape[0]),
            interpolation=cv2.INTER_NEAREST,
        )

    rgb_preview = rgb_bgr.copy()
    overlay_preview = overlay.copy()
    cv2.putText(
        rgb_preview,
        "Selected RGB frame",
        (15, 30),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.8,
        (0, 255, 0),
        2,
        cv2.LINE_AA,
    )
    cv2.putText(
        overlay_preview,
        "Segmentation result",
        (15, 30),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.8,
        (0, 255, 0),
        2,
        cv2.LINE_AA,
    )
    if not detected:
        cv2.putText(
            overlay_preview,
            "NO REGIONS DETECTED",
            (15, 65),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.7,
            (0, 0, 255),
            2,
            cv2.LINE_AA,
        )

    preview = np.hstack((rgb_preview, overlay_preview))
    cv2.imshow(PREVIEW_WINDOW, preview)
    key = cv2.waitKey(1) & 0xFF
    return key not in (ord("q"), ord("Q"), 27)


def process_recording(args: argparse.Namespace) -> int:
    if args.start_index < 0:
        raise ValueError("--start-index must be 0 or greater.")
    if args.max_frames < 0:
        raise ValueError("--max-frames must be 0 or greater.")

    input_dir = args.input_dir.resolve()
    hdf5_path = (
        args.h5.resolve()
        if args.h5 is not None
        else input_dir / DEFAULT_HDF5_NAME
    )
    print("Stage 1/2: extracting RGB and depth from HDF5...", flush=True)
    extracted_metadata_path = run_extraction_worker(hdf5_path, input_dir)
    print("Stage 2/2: loading CUDA segmentation runtime...", flush=True)
    load_processing_runtime()
    metadata_path = (
        args.metadata.resolve() if args.metadata is not None else extracted_metadata_path
    )
    metadata = load_metadata(metadata_path)
    rgb_sources = list_rgb_frames(input_dir, metadata)
    output_rgb_dir, overlay_dir, mask_dirs = create_and_clean_output_dirs(
        args.output.resolve()
    )

    print(f"Reading RGB frames from:   {rgb_sources[0].parent}")
    print(
        "Reading raw depth from:   "
        f"{input_dir / metadata['depth_directory']}"
    )
    print(f"Found synchronized pairs: {len(rgb_sources)}")
    print("Processing every captured pair.")
    print(f"Saving RGB frames to:     {output_rgb_dir}")
    print(f"Saving overlays to:       {overlay_dir}")
    print(f"Saving door masks to:     {mask_dirs['door']}")
    print(f"Saving wall masks to:     {mask_dirs['wall']}")
    print(f"Saving ground masks to:   {mask_dirs['ground']}")

    cache = FrameCache()
    processed = 0
    segmentacion.detener_hilo_secundario()
    segmentacion.inicializar(mode="prueba")

    if args.preview:
        cv2.namedWindow(PREVIEW_WINDOW, cv2.WINDOW_NORMAL)

    try:
        for source_offset, rgb_path in enumerate(rgb_sources):
            if args.max_frames > 0 and processed >= args.max_frames:
                break

            rgb_bgr, depth_m = load_frame_pair(
                rgb_path,
                input_dir,
                metadata,
            )
            cache.set_frame(rgb_bgr, depth_m)

            source_number = source_offset + 1
            overlay, detected, masks = process_frame(
                cache,
                source_number,
                args.retry,
                metadata["color_intrinsics"],
            )
            if overlay is None:
                overlay = rgb_bgr.copy()

            output_number = args.start_index + processed
            output_name = f"frame_{output_number:06d}.png"
            write_image(
                output_rgb_dir / output_name,
                rgb_bgr,
                "RGB frame",
            )
            write_image(
                overlay_dir / output_name,
                overlay,
                "segmentation overlay",
            )
            mask_images = {
                mask_key: binary_mask(
                    masks.get(mask_key),
                    rgb_bgr.shape[:2],
                )
                for mask_key in mask_dirs
            }
            mask_images["wall"] = cv2.bitwise_and(
                mask_images["wall"],
                cv2.bitwise_not(mask_images["ground"]),
            )

            for mask_key, mask_dir in mask_dirs.items():
                write_image(
                    mask_dir / output_name,
                    mask_images[mask_key],
                    f"{mask_key} mask",
                )

            processed += 1
            print(f"\rProcessed pairs: {processed}", end="", flush=True)
            if args.preview and not show_preview(rgb_bgr, overlay, detected):
                print("\nProcessing stopped from preview window.")
                break
    finally:
        segmentacion.detener_hilo_secundario()
        if args.preview:
            cv2.destroyAllWindows()

    print(f"\nDone. Processed {processed} synchronized RGB-D pairs.")
    return processed


def main() -> int:
    args = parse_args()
    if args.extract_only:
        input_dir = args.input_dir.resolve()
        hdf5_path = (
            args.h5.resolve()
            if args.h5 is not None
            else input_dir / DEFAULT_HDF5_NAME
        )
        extract_capture_hdf5(hdf5_path, input_dir)
        return 0
    process_recording(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
