"""Segment synchronized RGB and raw RealSense depth image pairs.

Input generated by captureVideo.py:

    tests/video/videos/RGB/frame_000001.png
    tests/video/videos/depth/frame_000001.png
    tests/video/videos/capture_metadata.json

Output:

    tests/video/data/RGB/frame_000001.png
    tests/video/data/overlay/frame_000001.png
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path
from typing import Optional

import cv2
import cupy as cp
import numpy as np

THIS_DIR = Path(__file__).resolve().parent
REPO_ROOT = THIS_DIR.parents[1]
SRC_DIR = REPO_ROOT / "src"
for path in (REPO_ROOT, SRC_DIR):
    path_str = str(path)
    if path_str not in sys.path:
        sys.path.insert(0, path_str)

from application.gestorFotogramas import dataset_frames  # noqa: E402
from application.segmentacion import segmentacion  # noqa: E402


DEFAULT_INPUT_DIR = THIS_DIR / "videos"
DEFAULT_OUTPUT_DIR = THIS_DIR / "data"
PREVIEW_WINDOW = "Frame processing: RGB | Segmentation (Q or Esc to stop)"


class FrameCache:
    """Expose one in-memory RGB-D pair through the dataset loader API."""

    def __init__(self) -> None:
        self.rgb_bgr: Optional[np.ndarray] = None
        self.depth_m: Optional[np.ndarray] = None

    def set_frame(self, rgb_bgr: np.ndarray, depth_m: np.ndarray) -> None:
        self.rgb_bgr = rgb_bgr
        self.depth_m = depth_m

    def load(self, index=None):
        del index
        if self.rgb_bgr is None or self.depth_m is None:
            return None, None
        return self.rgb_bgr, self.depth_m


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Segment synchronized RGB and raw depth PNG pairs."
    )
    parser.add_argument(
        "--input",
        "--video-dir",
        dest="input_dir",
        type=Path,
        default=DEFAULT_INPUT_DIR,
        help="Folder containing RGB/, depth/, and capture_metadata.json.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Output folder where RGB/ and overlay/ are created.",
    )
    parser.add_argument(
        "--metadata",
        type=Path,
        default=None,
        help="Metadata path. Defaults to input/capture_metadata.json.",
    )
    parser.add_argument(
        "--start-index",
        type=int,
        default=1,
        help="First number used for output filenames.",
    )
    parser.add_argument(
        "--max-frames",
        type=int,
        default=0,
        help="Maximum selected pairs to process. Use 0 for all.",
    )
    parser.add_argument(
        "--retry",
        type=int,
        default=2,
        help="Additional segmentation attempts when no mask is detected.",
    )
    parser.add_argument(
        "--no-preview",
        action="store_false",
        dest="preview",
        help="Process without opening the RGB/segmentation window.",
    )
    parser.set_defaults(preview=True)
    return parser.parse_args()


def load_metadata(path: Path) -> dict:
    if not path.is_file():
        raise FileNotFoundError(
            f"Capture metadata not found: {path}. Run captureVideo.py first."
        )

    metadata = json.loads(path.read_text(encoding="utf-8"))
    if metadata.get("rgb_storage") != "png_sequence":
        raise ValueError(
            "Unsupported RGB storage. Record again with the updated "
            "captureVideo.py to create synchronized PNG pairs."
        )
    if metadata.get("depth_storage") != "uint16_png_sequence":
        raise ValueError(
            "Unsupported depth storage. Record again with the updated "
            "captureVideo.py to store raw uint16 depth."
        )
    if float(metadata.get("depth_scale", 0)) <= 0:
        raise ValueError("capture_metadata.json has an invalid depth_scale.")

    intrinsics = metadata.get("color_intrinsics")
    if not isinstance(intrinsics, dict):
        raise ValueError("capture_metadata.json has no color_intrinsics.")
    for key in ("width", "height", "fx", "fy", "ppx", "ppy"):
        if key not in intrinsics:
            raise ValueError(f"Missing color_intrinsics.{key} in {path}")
    return metadata


def create_and_clean_output_dirs(output_dir: Path) -> tuple[Path, Path]:
    rgb_dir = output_dir / "RGB"
    overlay_dir = output_dir / "overlay"

    for directory in (rgb_dir, overlay_dir):
        directory.mkdir(parents=True, exist_ok=True)
        for item in directory.iterdir():
            if item.is_symlink() or item.is_file():
                item.unlink()
            elif item.is_dir():
                shutil.rmtree(item)
            else:
                item.unlink()

    return rgb_dir, overlay_dir


def list_rgb_frames(input_dir: Path, metadata: dict) -> list[Path]:
    rgb_dir = input_dir / metadata.get("rgb_directory", "RGB")
    frames = sorted(rgb_dir.glob("frame_*.png"))
    if not frames:
        raise FileNotFoundError(f"No RGB frames found in: {rgb_dir}")
    return frames


def load_frame_pair(
    rgb_path: Path,
    input_dir: Path,
    metadata: dict,
) -> tuple[np.ndarray, np.ndarray]:
    depth_dir = input_dir / metadata.get("depth_directory", "depth")
    depth_path = depth_dir / rgb_path.name

    rgb_bgr = cv2.imread(str(rgb_path), cv2.IMREAD_COLOR)
    depth_raw = cv2.imread(str(depth_path), cv2.IMREAD_UNCHANGED)
    if rgb_bgr is None:
        raise RuntimeError(f"Could not read RGB frame: {rgb_path}")
    if depth_raw is None:
        raise RuntimeError(
            f"RGB frame has no associated depth frame: {depth_path}"
        )
    if depth_raw.ndim != 2 or depth_raw.dtype != np.uint16:
        raise ValueError(
            f"Depth must be a single-channel uint16 PNG: {depth_path}; "
            f"received shape={depth_raw.shape}, dtype={depth_raw.dtype}."
        )

    if depth_raw.shape != rgb_bgr.shape[:2]:
        depth_raw = cv2.resize(
            depth_raw,
            (rgb_bgr.shape[1], rgb_bgr.shape[0]),
            interpolation=cv2.INTER_NEAREST,
        )

    depth_scale = float(metadata["depth_scale"])
    depth_m = depth_raw.astype(np.float32) * depth_scale
    return rgb_bgr, depth_m


def compute_rays(
    intrinsics: dict,
    shape_hw: tuple[int, int],
) -> np.ndarray:
    height, width = shape_hw
    scale_x = width / float(intrinsics["width"])
    scale_y = height / float(intrinsics["height"])
    fx = float(intrinsics["fx"]) * scale_x
    fy = float(intrinsics["fy"]) * scale_y
    ppx = float(intrinsics["ppx"]) * scale_x
    ppy = float(intrinsics["ppy"]) * scale_y

    u = np.arange(width, dtype=np.float32)
    v = np.arange(height, dtype=np.float32)
    uu, vv = np.meshgrid(u, v)
    x = (uu - ppx) / fx
    y = (vv - ppy) / fy
    return np.stack((x, y, np.ones_like(x)), axis=-1).astype(np.float32)


def apply_camera_geometry(intrinsics: dict, shape_hw: tuple[int, int]) -> None:
    runtime = segmentacion._obtener_impl()
    height, width = shape_hw
    runtime["H"] = height
    runtime["W"] = width
    runtime["rays_cp"] = cp.asarray(compute_rays(intrinsics, shape_hw))
    runtime["mode"] = "camera"


def mask_has_pixels(mask) -> bool:
    if mask is None:
        return False
    try:
        return bool(cp.any(mask).item())
    except Exception:
        return bool(np.any(np.asarray(mask)))


def process_frame(
    cache: FrameCache,
    dataset_index: int,
    retry: int,
    intrinsics: dict,
) -> tuple[Optional[np.ndarray], bool]:
    dataset_frames.load_dataset_frame = cache.load
    ok = segmentacion.preprocesar(
        mode="prueba",
        dataset_index=dataset_index,
    )
    if not ok or cache.rgb_bgr is None:
        return None, False

    apply_camera_geometry(intrinsics, cache.rgb_bgr.shape[:2])
    overlay = None
    detected = False
    attempts = max(0, int(retry)) + 1

    for attempt in range(attempts):
        try:
            overlay = segmentacion.segmentar()
            masks = segmentacion.obtener_mascaras(copy=False) or {}
            detected = any(mask_has_pixels(mask) for mask in masks.values())
        except Exception as exc:
            print(
                f"\nSegmentation attempt {attempt + 1}/{attempts} failed "
                f"for source frame {dataset_index}: {exc}",
                file=sys.stderr,
            )
            overlay = None
            detected = False

        if overlay is not None and detected:
            break

    return overlay, detected


def write_image(path: Path, image: np.ndarray, label: str) -> None:
    if not cv2.imwrite(str(path), image):
        raise RuntimeError(f"Could not save {label}: {path}")


def show_preview(
    rgb_bgr: np.ndarray,
    overlay: np.ndarray,
    detected: bool,
) -> bool:
    if overlay.shape[:2] != rgb_bgr.shape[:2]:
        overlay = cv2.resize(
            overlay,
            (rgb_bgr.shape[1], rgb_bgr.shape[0]),
            interpolation=cv2.INTER_NEAREST,
        )

    rgb_preview = rgb_bgr.copy()
    overlay_preview = overlay.copy()
    cv2.putText(
        rgb_preview,
        "Selected RGB frame",
        (15, 30),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.8,
        (0, 255, 0),
        2,
        cv2.LINE_AA,
    )
    cv2.putText(
        overlay_preview,
        "Segmentation result",
        (15, 30),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.8,
        (0, 255, 0),
        2,
        cv2.LINE_AA,
    )
    if not detected:
        cv2.putText(
            overlay_preview,
            "NO REGIONS DETECTED",
            (15, 65),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.7,
            (0, 0, 255),
            2,
            cv2.LINE_AA,
        )

    preview = np.hstack((rgb_preview, overlay_preview))
    cv2.imshow(PREVIEW_WINDOW, preview)
    key = cv2.waitKey(1) & 0xFF
    return key not in (ord("q"), ord("Q"), 27)


def process_recording(args: argparse.Namespace) -> int:
    if args.start_index < 0:
        raise ValueError("--start-index must be 0 or greater.")
    if args.max_frames < 0:
        raise ValueError("--max-frames must be 0 or greater.")

    input_dir = args.input_dir.resolve()
    metadata_path = (
        args.metadata.resolve()
        if args.metadata is not None
        else input_dir / "capture_metadata.json"
    )
    metadata = load_metadata(metadata_path)
    rgb_sources = list_rgb_frames(input_dir, metadata)
    output_rgb_dir, overlay_dir = create_and_clean_output_dirs(
        args.output.resolve()
    )

    print(f"Reading RGB frames from:   {rgb_sources[0].parent}")
    print(
        "Reading raw depth from:   "
        f"{input_dir / metadata.get('depth_directory', 'depth')}"
    )
    print(f"Found synchronized pairs: {len(rgb_sources)}")
    print("Processing every captured pair.")
    print(f"Saving RGB frames to:     {output_rgb_dir}")
    print(f"Saving overlays to:       {overlay_dir}")

    cache = FrameCache()
    processed = 0
    segmentacion.detener_hilo_secundario()
    segmentacion.inicializar(mode="prueba")

    if args.preview:
        cv2.namedWindow(PREVIEW_WINDOW, cv2.WINDOW_NORMAL)

    try:
        for source_offset, rgb_path in enumerate(rgb_sources):
            if args.max_frames > 0 and processed >= args.max_frames:
                break

            rgb_bgr, depth_m = load_frame_pair(
                rgb_path,
                input_dir,
                metadata,
            )
            cache.set_frame(rgb_bgr, depth_m)

            source_number = source_offset + 1
            overlay, detected = process_frame(
                cache,
                source_number,
                args.retry,
                metadata["color_intrinsics"],
            )
            if overlay is None:
                overlay = rgb_bgr.copy()

            output_number = args.start_index + processed
            output_name = f"frame_{output_number:06d}.png"
            write_image(
                output_rgb_dir / output_name,
                rgb_bgr,
                "RGB frame",
            )
            write_image(
                overlay_dir / output_name,
                overlay,
                "segmentation overlay",
            )

            processed += 1
            print(f"\rProcessed pairs: {processed}", end="", flush=True)
            if args.preview and not show_preview(rgb_bgr, overlay, detected):
                print("\nProcessing stopped from preview window.")
                break
    finally:
        segmentacion.detener_hilo_secundario()
        if args.preview:
            cv2.destroyAllWindows()

    print(f"\nDone. Processed {processed} synchronized RGB-D pairs.")
    return processed


def main() -> int:
    args = parse_args()
    process_recording(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
